### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by eullerpereira94** [lorensiuswlt/P25Demo#1]
Hi Lorensius, I've download your code for the demo and made some modifications, included some support for credit card reading, communicating with a remote server and printing receipts. And now I ask you for authorization to publish the code on Github. My wish is to make this application a case study for a real application I'm developing, and help others developers with the code I'm gonna publish. Can you give a thought for this?

**Comment by sreekanthsree000** [comment]
Hi Lorensius, I've download your code for the demo and made some modifications,but it connecting 5.0 and working fine.when i m connecting with kitkat lower versions it wil not connecting showing errors

08-24 12:48:46.525: W/BluetoothAdapter(22397): getBluetoothService() called with no BluetoothManagerCallback
08-24 12:48:46.615: D/BluetoothSocket(22397): connect(), SocketState: INIT, mPfd: {ParcelFileDescriptor: FileDescriptor[71]}
08-24 12:48:48.105: W/System.err(22397): java.io.IOException: read failed, socket might closed or timeout, read ret: -1
08-24 12:48:48.105: W/System.err(22397):    at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:581)
08-24 12:48:48.105: W/System.err(22397):    at android.bluetooth.BluetoothSocket.readInt(BluetoothSocket.java:592)
08-24 12:48:48.105: W/System.err(22397):    at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:370)
08-24 12:48:48.105: W/System.err(22397):    at net.londatiga.android.bluebamboo.P25Connector$ConnectTask.doInBackground(P25Connector.java:132)
08-24 12:48:48.105: W/System.err(22397):    at net.londatiga.android.bluebamboo.P25Connector$ConnectTask.doInBackground(P25Connector.java:1)
08-24 12:48:48.105: W/System.err(22397):    at android.os.AsyncTask$2.call(AsyncTask.java:288)
08-24 12:48:48.105: W/System.err(22397):    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-24 12:48:48.105: W/System.err(22397):    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
08-24 12:48:48.105: W/System.err(22397):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
08-24 12:48:48.105: W/System.err(22397):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
08-24 12:48:48.105: W/System.err(22397):    at java.lang.Thread.run(Thread.java:841)

**Comment by gzp1124** [comment]
You this project is using Bluetooth printing, 
but I would like to use WiFi printing.
Do you have a good project?
